"""
Complete Master Opening Variations Database
==========================================

All 20+ professional opening variations with deep theoretical knowledge,
rating stratification, and style-based classification.
"""

MASTER_OPENING_VARIATIONS = [
    {
        "id": "RuyLopez_Berlin",
        "eco": "C65-C67",
        "name": "Ruy Lopez",
        "variation": "Berlin Defense",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "Nxe4", "d4", "Nd6", "Bc4", "Be7", "dxe5", "Nxc4", "Qe2", "Nb6", "Bb3", "O-O", "Rd1", "Qe8"],
        "depth_moves": 20,
        "skill_levels": ["1400-2000", "2000+"],
        "key_ideas": "Solid endgame-friendly line; Black trades into a knight-and-pawn minor-piece endgame often favorable for draw-seeking or high-level maneuvering.",
        "typical_plans": "White: avoid simplifications or press with c4 and Nc3; Black: exchange pieces, use active king safety and pawn structure symmetry.",
        "traps_and_tactics": "Watch for tactics around e5 and d4; precise move-order matters to avoid falling into inferior endgames.",
        "transpositions": "Can transpose from Berlin to typical Ruy Lopez Closed lines if Black delays Nxe4.",
        "popularity_by_rating": {"1400-1800": 0.15, "1800-2200": 0.35, "2200+": 0.45},
        "typical_game_length": 65,
        "complexity_score": 7.5,
        "aggressive_score": 4.0,
        "positional_score": 8.5
    },
    {
        "id": "RuyLopez_Closed",
        "eco": "C84",
        "name": "Ruy Lopez",
        "variation": "Closed - Chigorin/Morphy style",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "b5", "Bb3", "d6", "c3", "O-O", "h3", "Nb8", "d4", "Nbd7"],
        "depth_moves": 20,
        "skill_levels": ["1400-2000", "2000+"],
        "key_ideas": "Classic maneuvering game; White builds center then kingside play, Black seeks counterplay on the queenside and central breaks.",
        "typical_plans": "White: c3, d4, Nbd2-f1-g3, f4 push. Black: ...c5 break, ...b4 to dislodge c3, or ...d5 when prepared.",
        "traps_and_tactics": "Watch early tactical shots around f7 and weak c3 squares; timing of ...c5 is critical.",
        "transpositions": "Often transposes to Closed Ruy Lopez sub-variations (Breyer, Zaitsev) depending on move order.",
        "popularity_by_rating": {"1400-1800": 0.25, "1800-2200": 0.40, "2200+": 0.30},
        "typical_game_length": 55,
        "complexity_score": 6.5,
        "aggressive_score": 5.5,
        "positional_score": 8.0
    },
    {
        "id": "RuyLopez_Marshall",
        "eco": "C88",
        "name": "Ruy Lopez",
        "variation": "Marshall Attack",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "b5", "Bb3", "O-O", "c3", "d5", "exd5", "Nxd5", "Nxe5", "Nxe5", "Rxe5", "c6", "Bc2", "Nf4", "g3", "Nxh3+", "Kg2", "Qg5"],
        "depth_moves": 20,
        "skill_levels": ["1800-2200+"],
        "key_ideas": "Sharp gambit where Black sacrifices a pawn for long-term activity and kingside attack — commonly seen at top-level play.",
        "typical_plans": "Black: piece activity, kingside initiative. White: avoid getting into concrete tactical lines unprepared; anti-Marshall moves exist (a4, h3).",
        "traps_and_tactics": "Deep theory; tactical sequences often decide the game early if either side strays from known theory.",
        "transpositions": "Can be sidestepped by White with move-order anti-Marshall systems (e.g., a4 or Re1 without c3).",
        "popularity_by_rating": {"1800-2200": 0.20, "2200+": 0.35},
        "typical_game_length": 45,
        "complexity_score": 9.5,
        "aggressive_score": 9.0,
        "positional_score": 6.0
    },
    {
        "id": "Sicilian_Najdorf",
        "eco": "B90-B99",
        "name": "Sicilian Defense",
        "variation": "Najdorf",
        "moves": ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6", "Be3", "e5", "Nb3", "Be6", "f3", "Be7", "Qd2", "O-O", "O-O-O", "b5", "g4", "b4", "Nd5", "Bxd5", "exd5", "Rc8"],
        "depth_moves": 20,
        "skill_levels": ["1600-2200+"],
        "key_ideas": "Complex asymmetrical fight; Black seeks queenside counterplay while White storms the kingside in many lines.",
        "typical_plans": "White: pawn storm with g4-h4 (English Attack) or positional schemes with f3 and K-side attack. Black: ...b5, ...Rc8, ...d5 break.",
        "traps_and_tactics": "Sharp tactics around pawn storms and sacrifices on g5/h4; watch typical exchange sacrifices on c3 or e4.",
        "transpositions": "Many transpositions into Scheveningen, Classical, or English Attack depending on move order.",
        "popularity_by_rating": {"1600-2000": 0.30, "2000+": 0.45},
        "typical_game_length": 50,
        "complexity_score": 9.0,
        "aggressive_score": 8.5,
        "positional_score": 6.5
    },
    {
        "id": "Sicilian_Sveshnikov",
        "eco": "B33-B34",
        "name": "Sicilian Defense",
        "variation": "Sveshnikov",
        "moves": ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e5", "Ndb5", "d6", "Bg5", "a6", "Na3", "b5", "Bxf6", "gxf6", "Nd5", "f5", "exf5", "Bxf5", "Bd3", "Bg6", "Qh5", "Rc8"],
        "depth_moves": 20,
        "skill_levels": ["1600-2200+"],
        "key_ideas": "Dynamic imbalance: Black accepts structural weaknesses (d6 pawn, doubled f-pawns) for active piece play and control of d4.",
        "typical_plans": "White: use d5 square, launch kingside play or piece maneuvers to exploit weak pawns. Black: seize initiative with ...f5, ...Be6 and pressure d4.",
        "traps_and_tactics": "Tactical sharpness around the d5 outpost and kingside pawn storms.",
        "transpositions": "Can transpose from Classical Sicilian lines depending on early ...e5 timing.",
        "popularity_by_rating": {"1600-2000": 0.20, "2000+": 0.30},
        "typical_game_length": 48,
        "complexity_score": 8.5,
        "aggressive_score": 8.0,
        "positional_score": 7.0
    },
    {
        "id": "Sicilian_Dragon",
        "eco": "B70-B79",
        "name": "Sicilian Defense",
        "variation": "Dragon",
        "moves": ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6", "Be3", "Bg7", "f3", "Nc6", "Qd2", "O-O", "Bc4", "Bd7", "O-O-O", "Rc8", "Bb3", "Ne5", "h4", "h5", "Bh6", "Bxh6", "Qxh6"],
        "depth_moves": 20,
        "skill_levels": ["1400-2200+"],
        "key_ideas": "Sharp opposite-side castling leads to mutual attacks: White on kingside, Black counter on queenside and center.",
        "typical_plans": "White: Yugoslav Attack with h4-h5 and sacrificial ideas. Black: pawn storms on queenside with ...b5, ...a5 and piece pressure.",
        "traps_and_tactics": "Many sacrificial motifs (Bxh6, Nd5) and mating patterns; precise move orders necessary at higher levels.",
        "transpositions": "May transpose into accelerated Dragon or other Sicilian tying to ...g6 setups.",
        "popularity_by_rating": {"1400-1800": 0.15, "1800-2200": 0.25, "2200+": 0.20},
        "typical_game_length": 45,
        "complexity_score": 9.5,
        "aggressive_score": 9.5,
        "positional_score": 5.0
    },
    {
        "id": "Queens_Gambit_Declined",
        "eco": "D30-D69",
        "name": "Queen's Gambit",
        "variation": "Declined - Orthodox",
        "moves": ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Be7", "e3", "O-O", "Nf3", "Nbd7", "Rc1", "c6", "Bd3", "dxc4", "Bxc4", "Nd5", "Bxe7", "Qxe7", "Ne4", "Nxc3", "Rxc3", "e5"],
        "depth_moves": 20,
        "skill_levels": ["1200-2200+"],
        "key_ideas": "Classical central pawn tension; Black maintains solid pawn structure while White seeks space advantage and kingside initiative.",
        "typical_plans": "White: central control, kingside attack, f3-e4 pawn advance. Black: solid development, ...c5 break, piece activity on queenside.",
        "traps_and_tactics": "Watch for tactical motifs around central pawns and piece exchanges; timing of releases crucial.",
        "transpositions": "Can transpose to many QGD variations including Tartakower, Semi-Tarrasch.",
        "popularity_by_rating": {"1200-1600": 0.35, "1600-2000": 0.40, "2000+": 0.25},
        "typical_game_length": 60,
        "complexity_score": 6.0,
        "aggressive_score": 4.5,
        "positional_score": 8.5
    },
    {
        "id": "Kings_Indian_Classical",
        "eco": "E90-E99",
        "name": "King's Indian Defense",
        "variation": "Classical - Mar del Plata",
        "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5", "O-O", "Nc6", "d5", "Ne7", "b4", "Nh5", "Re1", "f5", "Ng5", "Nf6", "f3", "f4", "b5", "g5"],
        "depth_moves": 20,
        "skill_levels": ["1400-2200+"],
        "key_ideas": "Dynamic kingside attack for Black vs White's queenside expansion; complex pawn structures with mutual chances.",
        "typical_plans": "White: queenside play with c5, space advantage. Black: kingside pawn storm with ...f5-f4, ...g5-g4, piece sacrifices.",
        "traps_and_tactics": "Sharp tactical sequences around pawn storms and piece sacrifices; timing is everything.",
        "transpositions": "May transpose into various King's Indian systems depending on White's setup.",
        "popularity_by_rating": {"1400-1800": 0.20, "1800-2200": 0.30, "2200+": 0.25},
        "typical_game_length": 52,
        "complexity_score": 8.5,
        "aggressive_score": 8.5,
        "positional_score": 6.5
    },
    {
        "id": "Nimzo_Indian_Classical",
        "eco": "E32-E39",
        "name": "Nimzo-Indian Defense",
        "variation": "Classical - 4.Qc2",
        "moves": ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "Qc2", "O-O", "a3", "Bxc3+", "Qxc3", "b6", "Bg5", "Bb7", "e3", "d6", "Bd3", "Nbd7", "Ne2", "c5", "O-O", "Rc8", "Rfd1", "cxd4"],
        "depth_moves": 20,
        "skill_levels": ["1400-2200+"],
        "key_ideas": "Black controls e4 square and seeks central pawn breaks; White builds kingside attack and central dominance.",
        "typical_plans": "White: e3-e4 advance, kingside attack, central control. Black: ...c5 break, piece activity, solid structure.",
        "traps_and_tactics": "Central tactics around d4 and e4; watch for tactical exchanges and pawn breaks.",
        "transpositions": "Can transpose into various Nimzo-Indian lines depending on White's choice of moves.",
        "popularity_by_rating": {"1400-1800": 0.25, "1800-2200": 0.35, "2200+": 0.30},
        "typical_game_length": 58,
        "complexity_score": 7.0,
        "aggressive_score": 5.5,
        "positional_score": 8.0
    },
    {
        "id": "French_Winawer",
        "eco": "C15-C19",
        "name": "French Defense",
        "variation": "Winawer - Poisoned Pawn",
        "moves": ["e4", "e6", "d4", "d5", "Nc3", "Bb4", "e5", "c5", "a3", "Bxc3+", "bxc3", "Ne7", "Qg4", "Qc7", "Qxg7", "Rg8", "Qxh7", "cxd4", "Ne2", "Nbc6", "f4", "Bd7", "Qd3", "dxc3"],
        "depth_moves": 20,
        "skill_levels": ["1600-2200+"],
        "key_ideas": "Sharp tactical battle; White sacrifices for attack while Black seeks counterplay with material advantage.",
        "typical_plans": "White: kingside attack, exploit weakened king position. Black: return material for safety, activate pieces.",
        "traps_and_tactics": "Highly tactical with many forcing sequences; precise calculation required.",
        "transpositions": "Part of broader Winawer complex; many sub-variations possible.",
        "popularity_by_rating": {"1600-2000": 0.15, "2000+": 0.25},
        "typical_game_length": 45,
        "complexity_score": 9.0,
        "aggressive_score": 9.5,
        "positional_score": 5.5
    },
    {
        "id": "Caro_Kann_Advance",
        "eco": "B12",
        "name": "Caro-Kann Defense",
        "variation": "Advance - Short System",
        "moves": ["e4", "c6", "d4", "d5", "e5", "Bf5", "Nf3", "e6", "Be2", "c5", "Be3", "Qb6", "Nc3", "Nc6", "a3", "c4", "O-O", "Bc2", "Re1", "h6", "Nh4", "Bh7", "f4", "g6"],
        "depth_moves": 20,
        "skill_levels": ["1200-2000+"],
        "key_ideas": "Space advantage for White vs solid structure for Black; complex middlegame maneuvering.",
        "typical_plans": "White: kingside attack, exploit space. Black: undermine center, seek pawn breaks on queenside.",
        "traps_and_tactics": "Central pawn tension creates tactical opportunities; watch for pawn breaks.",
        "transpositions": "May transpose into various Caro-Kann advance systems.",
        "popularity_by_rating": {"1200-1600": 0.30, "1600-2000": 0.25, "2000+": 0.15},
        "typical_game_length": 55,
        "complexity_score": 6.5,
        "aggressive_score": 6.0,
        "positional_score": 7.5
    },
    {
        "id": "English_Symmetrical",
        "eco": "A30-A39",
        "name": "English Opening",
        "variation": "Symmetrical - Hedgehog",
        "moves": ["c4", "c5", "Nf3", "Nf6", "g3", "b6", "Bg2", "Bb7", "O-O", "e6", "Nc3", "Be7", "d4", "cxd4", "Qxd4", "d6", "Rd1", "a6", "b3", "Nbd7", "Bb2", "Rc8", "Rac1", "O-O"],
        "depth_moves": 20,
        "skill_levels": ["1400-2200+"],
        "key_ideas": "Flexible pawn structure; White seeks central control while Black maintains solid hedgehog setup.",
        "typical_plans": "White: central pressure, piece activity. Black: solid structure, tactical counterplay when opportunity arises.",
        "traps_and_tactics": "Positional maneuvering with tactical shots; timing of central breaks crucial.",
        "transpositions": "Many possible transpositions into various English systems.",
        "popularity_by_rating": {"1400-1800": 0.20, "1800-2200": 0.30, "2200+": 0.25},
        "typical_game_length": 62,
        "complexity_score": 6.5,
        "aggressive_score": 5.0,
        "positional_score": 8.5
    },
    {
        "id": "Catalan_Open",
        "eco": "E04-E09",
        "name": "Catalan Opening",
        "variation": "Open - Main Line",
        "moves": ["d4", "Nf6", "c4", "e6", "g3", "d5", "Bg2", "dxc4", "Nf3", "Nc6", "O-O", "Rb8", "a4", "Bd7", "Qc2", "b5", "axb5", "Nxb5", "Qxc4", "Bb4", "Nbd2", "O-O", "Qc2", "a5"],
        "depth_moves": 20,
        "skill_levels": ["1600-2200+"],
        "key_ideas": "White's fianchettoed bishop creates long-term pressure; Black seeks active piece play to compensate.",
        "typical_plans": "White: central control, long diagonal pressure. Black: piece activity, tactical complications.",
        "traps_and_tactics": "Pressure along long diagonal creates tactical motifs; precise calculation needed.",
        "transpositions": "Can arise from Queen's Gambit or by direct move order.",
        "popularity_by_rating": {"1600-2000": 0.25, "2000+": 0.35},
        "typical_game_length": 58,
        "complexity_score": 7.5,
        "aggressive_score": 6.0,
        "positional_score": 8.0
    },
    {
        "id": "Grunfeld_Exchange",
        "eco": "D85-D89",
        "name": "Grünfeld Defense",
        "variation": "Exchange - Russian System",
        "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "d5", "cxd5", "Nxd5", "e4", "Nxc3", "bxc3", "Bg7", "Nf3", "c5", "Rb1", "O-O", "Be2", "cxd4", "cxd4", "Qa5+", "Bd2", "Qxa2", "O-O", "Bg4"],
        "depth_moves": 20,
        "skill_levels": ["1600-2200+"],
        "key_ideas": "Dynamic central tension; Black challenges White's pawn center while White seeks to maintain central dominance.",
        "typical_plans": "White: maintain center, kingside attack. Black: pressure central pawns, piece activity.",
        "traps_and_tactics": "Sharp central tactics; accurate calculation essential for both sides.",
        "transpositions": "Part of broader Grünfeld complex with many sub-variations.",
        "popularity_by_rating": {"1600-2000": 0.20, "2000+": 0.30},
        "typical_game_length": 50,
        "complexity_score": 8.0,
        "aggressive_score": 7.5,
        "positional_score": 7.0
    },
    {
        "id": "Alekhine_Four_Pawns",
        "eco": "B03",
        "name": "Alekhine's Defense",
        "variation": "Four Pawns Attack",
        "moves": ["e4", "Nf6", "e5", "Nd5", "d4", "d6", "c4", "Nb6", "f4", "dxe5", "fxe5", "Nc6", "Be3", "Bf5", "Nc3", "e6", "Nf3", "Qd7", "Be2", "O-O-O", "O-O", "h6", "a4", "a5"],
        "depth_moves": 20,
        "skill_levels": ["1400-2000+"],
        "key_ideas": "White's aggressive pawn storm vs Black's piece activity; sharp tactical play with opposite-side castling.",
        "typical_plans": "White: maintain central pawns, kingside attack. Black: undermine center, piece pressure.",
        "traps_and_tactics": "Sharp tactics around central pawns and opposite-side castling attacks.",
        "transpositions": "Main line of Alekhine's Defense with various sub-continuations.",
        "popularity_by_rating": {"1400-1800": 0.15, "1800-2000": 0.20, "2000+": 0.10},
        "typical_game_length": 47,
        "complexity_score": 7.5,
        "aggressive_score": 8.5,
        "positional_score": 6.0
    },
    {
        "id": "Pirc_Austrian",
        "eco": "B09",
        "name": "Pirc Defense",
        "variation": "Austrian Attack",
        "moves": ["e4", "d6", "d4", "Nf6", "Nc3", "g6", "f4", "Bg7", "Nf3", "O-O", "Bd3", "Na6", "O-O", "c5", "d5", "Rb8", "a4", "Nc7", "h3", "b5", "axb5", "Nxb5", "Nxb5", "Rxb5"],
        "depth_moves": 20,
        "skill_levels": ["1400-2000+"],
        "key_ideas": "White's space advantage and kingside attack vs Black's counterplay on queenside and central breaks.",
        "typical_plans": "White: f4-f5 pawn storm, kingside attack. Black: ...c5 break, queenside counterplay.",
        "traps_and_tactics": "Sharp kingside attacks meet central counter-strikes; tactical alertness required.",
        "transpositions": "May transpose into King's Indian structures or remain in Pirc systems.",
        "popularity_by_rating": {"1400-1800": 0.10, "1800-2000": 0.15, "2000+": 0.10},
        "typical_game_length": 48,
        "complexity_score": 7.0,
        "aggressive_score": 8.0,
        "positional_score": 6.5
    },
    {
        "id": "Benko_Gambit",
        "eco": "A57-A59",
        "name": "Benko Gambit",
        "variation": "Accepted - Main Line",
        "moves": ["d4", "Nf6", "c4", "c5", "d5", "b5", "cxb5", "a6", "bxa6", "Bxa6", "Nc3", "d6", "e4", "Bxf1", "Kxf1", "g6", "g3", "Bg7", "Kg2", "O-O", "Nf3", "Nbd7", "h3", "Qb6"],
        "depth_moves": 20,
        "skill_levels": ["1600-2200+"],
        "key_ideas": "Black sacrifices pawn for long-term pressure on queenside; White must defend accurately while consolidating.",
        "typical_plans": "Black: queenside pressure, piece activity. White: consolidate extra pawn, central control.",
        "traps_and_tactics": "Long-term positional pressure with tactical shots; patience required from both sides.",
        "transpositions": "Specific gambit line with limited transposition possibilities.",
        "popularity_by_rating": {"1600-2000": 0.10, "2000+": 0.15},
        "typical_game_length": 55,
        "complexity_score": 7.5,
        "aggressive_score": 6.5,
        "positional_score": 7.5
    },
    {
        "id": "Dutch_Leningrad",
        "eco": "A80-A99",
        "name": "Dutch Defense",
        "variation": "Leningrad - Main Line",
        "moves": ["d4", "f5", "g3", "Nf6", "Bg2", "g6", "Nf3", "Bg7", "O-O", "O-O", "c4", "d6", "Nc3", "Qe8", "d5", "Na6", "Rb1", "Nc5", "b4", "Nce4", "Nxe4", "Nxe4", "Bb2", "a5"],
        "depth_moves": 20,
        "skill_levels": ["1400-2000+"],
        "key_ideas": "Black's kingside attack with f5-f4 thrust vs White's central and queenside expansion.",
        "typical_plans": "Black: kingside attack with f4, piece activity. White: central control, queenside play.",
        "traps_and_tactics": "Kingside attacks meet positional maneuvering; both sides have attacking chances.",
        "transpositions": "May transpose into various Dutch systems or King's Indian-like structures.",
        "popularity_by_rating": {"1400-1800": 0.15, "1800-2000": 0.20, "2000+": 0.10},
        "typical_game_length": 52,
        "complexity_score": 6.5,
        "aggressive_score": 7.5,
        "positional_score": 6.5
    },
    {
        "id": "Modern_Defense",
        "eco": "B06",
        "name": "Modern Defense",
        "variation": "Main Line with ...Nd7",
        "moves": ["e4", "g6", "d4", "Bg7", "Nc3", "d6", "f4", "Nd7", "Nf3", "e5", "Bb5", "a6", "Bxd7+", "Bxd7", "fxe5", "dxe5", "d5", "f5", "exf5", "Bxf5", "O-O", "Ne7", "Nh4", "Bd7"],
        "depth_moves": 20,
        "skill_levels": ["1400-2000+"],
        "key_ideas": "Flexible hypermodern setup; Black delays central commitments while maintaining piece activity.",
        "typical_plans": "White: central control, space advantage. Black: flexible development, central counter-strikes when ready.",
        "traps_and_tactics": "Positional maneuvering with tactical opportunities; timing of central activity crucial.",
        "transpositions": "May transpose into Pirc or King's Indian structures depending on development.",
        "popularity_by_rating": {"1400-1800": 0.10, "1800-2000": 0.15, "2000+": 0.10},
        "typical_game_length": 54,
        "complexity_score": 6.0,
        "aggressive_score": 5.5,
        "positional_score": 7.0
    },
    {
        "id": "Scandinavian_Main",
        "eco": "B01",
        "name": "Scandinavian Defense",
        "variation": "Main Line - 3...Qa5",
        "moves": ["e4", "d5", "exd5", "Qxd5", "Nc3", "Qa5", "d4", "Nf6", "Nf3", "Bf5", "Bc4", "e6", "Bd2", "c6", "Nd5", "Qd8", "Nxf6+", "gxf6", "O-O", "Nd7", "Re1", "Nb6", "Bb3", "Qd7"],
        "depth_moves": 20,
        "skill_levels": ["1200-1800+"],
        "key_ideas": "Early queen activity for Black seeks rapid development; White aims to exploit early queen exposure.",
        "typical_plans": "White: exploit queen exposure, central control. Black: rapid development, piece activity despite structural damage.",
        "traps_and_tactics": "Early tactical shots around exposed queen; development race crucial.",
        "transpositions": "Limited transposition opportunities; specific to Scandinavian systems.",
        "popularity_by_rating": {"1200-1600": 0.20, "1600-1800": 0.15, "1800+": 0.10},
        "typical_game_length": 45,
        "complexity_score": 5.5,
        "aggressive_score": 6.5,
        "positional_score": 5.5
    }
]