# Generated by Django 5.1.1 on 2025-09-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_blitz_r_7648bd_idx',
            old_name='chess_users_blitz_r_5b40b8_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_rapid_r_1e2b91_idx',
            old_name='chess_users_rapid_r_8b0a62_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_classic_75c2d9_idx',
            old_name='chess_users_classic_b69ca3_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_is_onli_95e73e_idx',
            old_name='chess_users_is_onli_3dd828_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_last_ac_6ec725_idx',
            old_name='chess_users_last_ac_3e3229_idx',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
    ]
