# Generated by Django 5.1.1 on 2025-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_chess_users_blitz_r_5b40b8_idx_accounts_cu_blitz_r_7648bd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initial_skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Initial skill level selected during registration', max_length=15, null=True),
        ),
    ]
