# Generated by Django 5.1.1 on 2025-09-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical'), ('custom', 'Custom')], max_length=10)),
                ('initial_time', models.IntegerField(help_text='Initial time in seconds')),
                ('increment', models.IntegerField(default=0, help_text='Increment per move in seconds')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'time_controls',
                'ordering': ['category', 'initial_time'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', help_text='Current board position in FEN', max_length=200)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'In progress'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='waiting', max_length=20)),
                ('result', models.CharField(choices=[('1-0', 'White wins'), ('0-1', 'Black wins'), ('1/2-1/2', 'Draw'), ('*', 'Game in progress')], default='*', max_length=10)),
                ('termination', models.CharField(blank=True, choices=[('checkmate', 'Checkmate'), ('resignation', 'Resignation'), ('timeout', 'Time out'), ('draw_agreement', 'Draw by agreement'), ('stalemate', 'Stalemate'), ('insufficient_material', 'Insufficient material'), ('threefold_repetition', 'Threefold repetition'), ('fifty_move_rule', 'Fifty-move rule'), ('abandoned', 'Game abandoned')], max_length=30, null=True)),
                ('white_time_remaining', models.IntegerField(default=0, help_text='Remaining time in seconds for white')),
                ('black_time_remaining', models.IntegerField(default=0, help_text='Remaining time in seconds for black')),
                ('last_move_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
                ('time_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.timecontrol')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('from_square', models.CharField(max_length=5)),
                ('to_square', models.CharField(max_length=5)),
                ('promotion', models.CharField(blank=True, max_length=1, null=True)),
                ('notation', models.CharField(max_length=20)),
                ('fen_after', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', help_text='FEN after move', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('elapsed_time', models.IntegerField(default=0, help_text='Seconds spent on this move')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moves',
                'ordering': ['move_number'],
                'indexes': [models.Index(fields=['game', 'move_number'], name='moves_game_id_325edd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_status_def24c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['created_at'], name='games_created_51ed57_idx'),
        ),
    ]
