# Generated by Django 5.1.1 on 2025-09-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional invitation message', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this invitation expires')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games_gameinvitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='game',
            old_name='last_move_time',
            new_name='last_move_at',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='fen_after',
            new_name='fen_after_move',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='elapsed_time',
            new_name='time_taken',
        ),
        migrations.RenameIndex(
            model_name='game',
            new_name='games_game_status_da80c5_idx',
            old_name='games_status_def24c_idx',
        ),
        migrations.RenameIndex(
            model_name='game',
            new_name='games_game_created_1f2afd_idx',
            old_name='games_created_51ed57_idx',
        ),
        migrations.RenameIndex(
            model_name='move',
            new_name='games_move_game_id_ebaa0c_idx',
            old_name='moves_game_id_325edd_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='black_time_remaining',
        ),
        migrations.RemoveField(
            model_name='game',
            name='white_time_remaining',
        ),
        migrations.RemoveField(
            model_name='move',
            name='promotion',
        ),
        migrations.AddField(
            model_name='game',
            name='black_time_left',
            field=models.IntegerField(default=600, help_text='Remaining time in seconds for black'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_time_left',
            field=models.IntegerField(default=600, help_text='Remaining time in seconds for white'),
        ),
        migrations.AddField(
            model_name='move',
            name='captured_piece',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='is_castling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_checkmate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='is_en_passant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='promotion_piece',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='time_left',
            field=models.IntegerField(default=600, help_text='Time remaining after this move'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_control',
            field=models.CharField(default='rapid', help_text='Time control format', max_length=20),
        ),
        migrations.AlterModelTable(
            name='game',
            table='games_game',
        ),
        migrations.AlterModelTable(
            name='move',
            table='games_move',
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='from_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='time_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.timecontrol'),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='to_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['from_player', 'status'], name='games_gamei_from_pl_e80205_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['to_player', 'status'], name='games_gamei_to_play_be8690_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['created_at'], name='games_gamei_created_ddcb86_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['expires_at'], name='games_gamei_expires_843f47_idx'),
        ),
    ]
