# Generated by Django 5.2.5 on 2025-08-24 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['move_number']},
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_game_status_da80c5_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['created_at'], name='games_game_created_1f2afd_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['game', 'move_number'], name='games_move_game_id_ebaa0c_idx'),
        ),
    ]
