# Generated by Django 5.1.1 on 2025-09-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameinvitation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='time_left',
            new_name='time_left_after',
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn_start',
            field=models.DateTimeField(blank=True, help_text="When current player's turn started", null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='increment_added',
            field=models.IntegerField(default=0, help_text='Increment added after this move'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_move_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last move made', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_control',
            field=models.ForeignKey(blank=True, help_text='Time control settings for this game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.timecontrol'),
        ),
    ]
