# Generated by Django 5.1.1 on 2025-09-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_time_left_move_time_left_after_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='time_left_after',
            new_name='time_left',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_turn_start',
        ),
        migrations.RemoveField(
            model_name='move',
            name='increment_added',
        ),
        migrations.AlterField(
            model_name='game',
            name='last_move_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_control',
            field=models.CharField(default='rapid', help_text='Time control format', max_length=20),
        ),
    ]
