# Generated by Django 5.1.1 on 2025-12-29 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_time_left_after_move_time_left_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='External puzzle ID (e.g., from Lichess)', max_length=50, null=True, unique=True)),
                ('fen', models.CharField(help_text='Starting position in FEN notation', max_length=200)),
                ('solution', models.JSONField(help_text="List of moves in UCI format, e.g., ['e2e4', 'd7d5', 'e4d5']")),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Puzzle objective description')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('category', models.CharField(choices=[('tactics', 'Tactics'), ('endgame', 'Endgame'), ('opening', 'Opening'), ('strategy', 'Strategy'), ('checkmate', 'Checkmate Pattern'), ('defense', 'Defense')], default='tactics', max_length=20)),
                ('themes', models.JSONField(default=list, help_text='List of tactical themes')),
                ('rating', models.IntegerField(default=1500, help_text='Puzzle difficulty rating')),
                ('times_played', models.IntegerField(default=0)),
                ('times_solved', models.IntegerField(default=0)),
                ('average_time', models.FloatField(default=0.0, help_text='Average solve time in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_game', models.ForeignKey(blank=True, help_text='Original game this puzzle was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_puzzles', to='games.game')),
            ],
            options={
                'db_table': 'games_puzzle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('time_spent', models.FloatField(help_text='Time spent in seconds')),
                ('moves_made', models.JSONField(default=list, help_text='List of moves attempted')),
                ('hints_used', models.IntegerField(default=0)),
                ('rating_before', models.IntegerField(blank=True, null=True)),
                ('rating_after', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_puzzleattempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPuzzleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_rating', models.IntegerField(default=1500)),
                ('highest_rating', models.IntegerField(default=1500)),
                ('puzzles_attempted', models.IntegerField(default=0)),
                ('puzzles_solved', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('total_time_spent', models.FloatField(default=0.0, help_text='Total time in seconds')),
                ('tactics_solved', models.IntegerField(default=0)),
                ('endgame_solved', models.IntegerField(default=0)),
                ('opening_solved', models.IntegerField(default=0)),
                ('strategy_solved', models.IntegerField(default=0)),
                ('last_puzzle_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_userpuzzlestats',
            },
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['difficulty', 'category'], name='games_puzzl_difficu_ce821a_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['rating'], name='games_puzzl_rating_c07f90_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['is_active'], name='games_puzzl_is_acti_bb0728_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['user', 'puzzle'], name='games_puzzl_user_id_511dac_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['user', 'solved'], name='games_puzzl_user_id_dc29e7_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['created_at'], name='games_puzzl_created_cff203_idx'),
        ),
    ]
