# Generated by Django 5.1.1 on 2026-02-17 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_puzzle_puzzleattempt_userpuzzlestats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw_offered_by',
            field=models.ForeignKey(blank=True, help_text='User who offered a draw (null if no pending offer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_offers_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
